# Generated by Django 2.1.5 on 2019-02-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NriNotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
