# Generated by Django 2.1.5 on 2019-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NriNotes', '0002_auto_20190211_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
